### ISSUE TITLE
pygame issue

### ISSUE THREAD

**Issue by huang628** [oseiskar/raytracer#2]
Hi I was trying to run the raytracer - the program is running but pygame window never showed up. Have you ever encountered this issue? Thanks!

**Comment by oseiskar** [comment]
Hmm, I remember a similar issue on a certain laptop and traced it back to the use of [pygame.surfarray.make_surface](http://www.pygame.org/docs/ref/surfarray.html#pygame.surfarray.make_surface) on [this line](https://github.com/oseiskar/raytracer/blob/01e6c5d1024b367dd1a14ec3ef17da1c5d8f9dbe/imgutils.py#L82) but didn't really get it fixed. Seemed like a bug in Pygame itself.

I don't currently have that problem on this machine, which runs Debian Jessie with Nvidia driver version 352.63 and Pygame v.1.9.2a0.

I'll try to fix the issue if I encounter it again. Thanks for reporting.

**Comment by oseiskar** [comment]
I changed the default visualization library to PySDL2, which fixed the problems I had before. Now there are also some more installation instructions in README.md. Please reopen, if this did not fix the issue
